 
language: node_js
node_js:
  - "v9.11.2"
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_registrations
before_script:
  - psql -c 'CREATE DATABASE my_registrations;' -U postgres
  - psql -U postgres -d my_registrations -a -f table.sql